# Default values for scos-joomla.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploy:
  updateStrategy:
      type: RollingUpdate

storage:
  size: 10Gi
  mode: ReadWriteOnce

image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/joomla
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: scos-joomla
  port: 80
  type: NodePort

ingress:
  scheme: ""
  subnets: ""
  security_groups: ""
  root:
    enabled: true
    dns_zone: ""
    certificate_arns: ""
  internal:
    enabled: true
    dns_zone: ""
    certificate_arns: ""

resources:
  limits:
   cpu: 750m
   memory: 1Gi
  requests:
   cpu: 750m
   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
