apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.root.scheme }}
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-path: /health_check.php
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.security_groups }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.root.certificate_arns }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.response-404: '{"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"404","MessageBody":"404 - Page Not Found"}}'
    alb.ingress.kubernetes.io/actions.redirect-to-datajson: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "Host": "data.{{ .Values.ingress.root.dns_zone }}", "Path": "/api/v1/data_json", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.redirect-to-homepage: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "Host": "www.{{ .Values.ingress.root.dns_zone }}", "Path": "/data", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.redirect-api: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "Host": "data.{{ .Values.ingress.root.dns_zone }}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.root.waf_acl_arn }}
spec:
  backend:
    serviceName: {{ .Values.service.name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: www.{{ .Values.ingress.root.dns_zone }}
    http:
      paths:
      - path: /data.json
        backend:
          serviceName: redirect-to-datajson
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - host: {{ .Values.ingress.root.dns_zone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - host: ckan.{{ .Values.ingress.root.dns_zone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect-to-homepage
          servicePort: use-annotation
  - host: api.{{ .Values.ingress.root.dns_zone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect-api
          servicePort: use-annotation
  - http:
      paths:
      - path: /administrator*
        backend:
          serviceName: response-404
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-internal
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-path: /health_check.php
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.security_groups }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.internal.certificate_arns }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
spec:
  backend:
    serviceName: {{ .Values.service.name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: www.{{ .Values.ingress.internal.dns_zone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation